# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       friends-integration

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Friends integration plugin
Version:    0.1
Release:    1
Group:      Qt/Qt
License:    TODO
URL:        https://github.com/SfietKonstantin/friends-integration
Source0:    %{name}-%{version}.tar.bz2
Source100:  friends-integration.yaml
Requires:   harbour-friends
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Sql)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Contacts)
BuildRequires:  pkgconfig(buteosyncfw5)
BuildRequires:  pkgconfig(nemonotifications-qt5)
BuildRequires:  pkgconfig(accounts-qt5)

%description
Friends integration plugin allows
deeper integration between Friends
Facebook client and Sailfish OS

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

%post
# >> post
dbus-send --system --type=method_call \
--dest=org.freedesktop.DBus / org.freedesktop.DBus.ReloadConfig
# << post

%postun
# >> postun
dbus-send --system --type=method_call \
--dest=org.freedesktop.DBus / org.freedesktop.DBus.ReloadConfig
# << postun

%files
%defattr(-,root,root,-)
%{_datadir}/dbus-1/
%{_datadir}/accounts/
%{_libdir}/buteo-plugins-qt5
%{_sysconfdir}/buteo/profiles
%{_libdir}/qt5/qml/org/SfietKonstantin/friends/integration
%{_datadir}/lipstick/
# >> files
# << files
