# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       friends-integration

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Friends integration plugin
Version:    0.1
Release:    1
Group:      Qt/Qt
License:    LICENSE
URL:        http://example.org/
Source0:    %{name}-%{version}.tar.bz2
Source100:  friends-integration.yaml
Requires:   sailfish-components-contacts-qt5 = 0.1.20
Requires:   harbour-friends
Requires:   patch
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Contacts)
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Quick)

%description
Friends integration plugin allows
deeper integration between Friends
Facebook client and Sailfish OS

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

%preun
# >> preun
/opt/friends-integration/preun.sh
# << preun

%post
# >> post
/opt/friends-integration/post.sh
# << post

%files
%defattr(-,root,root,-)
/opt/friends-integration/
%{_libdir}/qt5/qml/org/SfietKonstantin/friends/integration
# >> files
# << files
